name: audrey
on:
  workflow_dispatch:
env:
  AREA: JP13
  STATION: LFR
  DAYWEEK: 0 # 0 (Sunday) to 6 (Saturday)
  TIME: "010000"
  TITLE: オードリーのオールナイトニッポン
jobs:
  record:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Detect previous program date
        id: prev-date
        run: |
          target_date=$(node src/get_date.js)
          echo "target_date=$target_date" >>$GITHUB_OUTPUT
      - name: check
        run:
          echo ${{ env.AREA}}
          echo ${{ steps.prev-date.outputs.target_date }}
          echo ${{ env.TIME }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
            platforms: linux/arm64
      - name: Docker build
        run: |
          docker build . -t radio-station
      - name: Docker run
        run: |
          docker run -v $PWD/output:/output -e RADIKO_MAIL="${{ secrets.RADIKO_MAIL }}" -e RADIKO_PASSWORD="${{ secrets.RADIKO_PASSWORD }}" radio-station rec -a=${{ env.AREA }} -id=${{ env.STATION }} -s=${{ steps.prev-date.outputs.target_date }}${{ env.TIME }}
